# Generated by Django 5.2.4 on 2025-09-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OcrDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_pdf_path', models.CharField(max_length=1024)),
                ('mineru_json_path', models.CharField(max_length=1024)),
                ('status', models.CharField(default='processed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
