# Generated by Django 5.1.12 on 2025-09-27 12:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrdocument",
            name="corrected_text_payload",
            field=models.JSONField(
                blank=True,
                help_text="The structured text payload after correction, ready for RAGFlow.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ocrdocument",
            name="doc_uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for external references.",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="ocrdocument",
            name="raw_ocr_json",
            field=models.JSONField(
                blank=True,
                help_text="Raw JSON output from the MinerU OCR engine.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ocrdocument",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="ocrdocument",
            name="mineru_json_path",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="ocrdocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Upload"),
                    ("processing", "OCR Processing"),
                    ("processed", "OCR Processed (Ready for Labeling)"),
                    ("failed", "OCR Failed"),
                    ("ingesting", "Ingesting to RAGFlow"),
                    ("labeled", "Labeled & Ingested"),
                    ("ingestion_failed", "RAGFlow Ingestion Failed"),
                ],
                default="pending",
                max_length=35,
            ),
        ),
    ]
