# Generated by Django 5.1.12 on 2025-09-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_ocrdocument_corrected_text_payload_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ocrdocument",
            name="corrected_text_payload",
        ),
        migrations.RemoveField(
            model_name="ocrdocument",
            name="doc_uuid",
        ),
        migrations.RemoveField(
            model_name="ocrdocument",
            name="raw_ocr_json",
        ),
        migrations.AlterField(
            model_name="ocrdocument",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ocrdocument",
            name="mineru_json_path",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="ocrdocument",
            name="status",
            field=models.CharField(default="processed", max_length=50),
        ),
    ]
