# Generated by Django 5.1.12 on 2025-09-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_ocrdocument_corrected_text_payload_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrdocument",
            name="corrected_label_studio_json",
            field=models.JSONField(blank=True, null=True, verbose_name="校对后的JSON"),
        ),
        migrations.AddField(
            model_name="ocrdocument",
            name="raw_ocr_json",
            field=models.JSONField(blank=True, null=True, verbose_name="原始OCR JSON"),
        ),
        migrations.AlterField(
            model_name="ocrdocument",
            name="mineru_json_path",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="ocrdocument",
            name="status",
            field=models.CharField(default="pending", max_length=50),
        ),
    ]
